from qlib.constant import REG_CN

# markets
REGION = REG_CN
INSTRUMENTS = "csi300"
DEAL_PRICE = "open"

# params
MODEL_LOSS = "mse"
LABEL_NORM = "CSRankNorm"
ENABLE_REWEIGHTER = False
ENABLE_NEUTRALIZE = False
ENABLE_GTJA_ALPHA = False

SEARCH_STRATEGY_PARAMS = True
SEARCH_MODEL_PARAMS = False
