from qlib.constant import REG_CN

# markets
REGION = REG_CN
INSTRUMENTS = "csi300"
DEAL_PRICE = "open"
DAYS_AHEAD = 4
HOLD_THRESH = 2

# params
LOSS_TYPE = "mse"
LABEL_NORM = "CSRankNorm"
ENABLE_REWEIGHTER = False
ENABLE_GTJA_ALPHA = False

SEARCH_STRATEGY_PARAMS = True
SEARCH_MODEL_PARAMS = False

ALL_CONFIG_KEY = f"{REGION}_{INSTRUMENTS}_{DEAL_PRICE}_{LABEL_NORM}_{LOSS_TYPE}"
